/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Book;
import beans.Document;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import managers.AdminLibraryManager;

/**
 *
 * @author BigBlackBug
 */
public class NewLibraryItemPanel extends javax.swing.JPanel {

    private AdminLibraryManager libraryManager;
    private JDialog parent;
    private DefaultListModel<String> listModel;
    AdminPanel adminPanel;

    /**
     * Creates new form UpdateLibraryPanel
     */
    public NewLibraryItemPanel(AdminPanel adminPanel, AdminLibraryManager adminLibraryManager, JDialog parent) {
        this.parent = parent;
        this.listModel = new DefaultListModel<>();
        this.adminPanel = adminPanel;
        this.libraryManager = adminLibraryManager;

        initComponents();
        initList();
        loadAll();
        resultList.setModel(listModel);
    }

    private void loadAll() {
        listModel.clear();
        List<Book> all = libraryManager.getBookDAO().getAll();
        for (Book d : all) {
            listModel.addElement(d.isbn);
        }
    }

    private void initList() {
        // listModel = new DefaultListModel<>();
        // resultsList.setModel(listModel);
        userInputTF.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void changedUpdate(DocumentEvent e) {
                processChange();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                processChange();
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                processChange();
            }

            private void processChange() {
                String text = userInputTF.getText();
                infoLabel.setText("");
                if (text.isEmpty() || text.trim().isEmpty()) {
                    // adminPanel.prepare();
                    loadAll();
                    return;
                }

                listModel.clear();
                List<Book> filter = libraryManager.getBookDAO().filter(text);
                if (filter.isEmpty()) {
                    infoLabel.setText("Book not found!");
                } else {
                    for (Book b : filter) {
                        listModel.addElement(b.isbn);
                    }
                }

                /*
                 * List<Map<String, Object>> filter =
                 * libraryManager.getStorageManager().filterAsMap(text);
                 * //listModel.clear(); if (filter.isEmpty()) {
                 * infoLabel.setText("There's no such book"); } else {
                 * infoLabel.setText(""); listModel.setData(filter); }
                 */
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoLabel = new javax.swing.JLabel();
        amountSpinner = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        userInputTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultList = new javax.swing.JList();

        jButton2.setText("fill");
        jButton2.setActionCommand("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        resultList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        resultList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(resultList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userInputTF)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(amountSpinner)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)))
                    .addComponent(infoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userInputTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        infoLabel.setText("");
        Integer amount = (Integer) amountSpinner.getValue();
        if (amount <= 0) {
            infoLabel.setText("the amount has to a positive number");
            return;
        }
        int selected = resultList.getSelectedIndex();
        libraryManager.getStorageManager().replenishLibrary(listModel.get(selected), amount);
        adminPanel.prepare();
        parent.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner amountSpinner;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList resultList;
    private javax.swing.JTextField userInputTF;
    // End of variables declaration//GEN-END:variables
}
